// ============================================================================
// 256-Point Radix-2 DIT FFT (Sequential)
// ============================================================================
// In-place butterfly computation using dual-port BRAM.
// 8 stages × 128 butterflies = 1024 butterflies total.
// ~4 clock cycles per butterfly → ~4096 cycles total (~164 µs at 25 MHz).
//
// Input: real-valued samples (imaginary = 0), loaded in natural order.
//        Module internally applies bit-reversal permutation.
// Output: complex frequency-domain values, streamed sequentially.
//
// Twiddle factors loaded from external .mem files (generated by Python).
// Data uses 16-bit signed fixed-point with >>1 scaling each stage
// to prevent overflow (total scaling = 1/256 = divide by N).
//
// Requires: tw_cos.mem, tw_sin.mem (128 entries each, signed hex16)
// ============================================================================

module fft_256 #(
    parameter DATA_W  = 16,
    parameter TW_FILE_COS = "tw_cos.mem",
    parameter TW_FILE_SIN = "tw_sin.mem"
)(
    input  wire                    clk,
    input  wire                    rst_n,
    // Control
    input  wire                    start,       // Pulse: begin FFT after all samples loaded
    output reg                     busy,        // High while processing
    output reg                     done,        // Pulse: FFT complete, output ready
    // Input write port (load samples before asserting start)
    input  wire signed [DATA_W-1:0] din_re,
    input  wire [7:0]              din_addr,    // Natural-order address
    input  wire                    din_we,
    // Output read port (valid after done)
    output wire signed [DATA_W-1:0] dout_re,
    output wire signed [DATA_W-1:0] dout_im,
    input  wire [7:0]              dout_addr
);

    // ── Bit-reversal function ──
    function [7:0] bit_rev;
        input [7:0] a;
        begin
            bit_rev = {a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]};
        end
    endfunction

    // ── Internal BRAM for FFT data ──
    reg signed [DATA_W-1:0] fft_re [0:255];
    reg signed [DATA_W-1:0] fft_im [0:255];

    // ── Twiddle factor ROM (Q1.15 signed) ──
    // W_N^k = cos(2πk/N) - j·sin(2πk/N)
    // tw_cos[k] = round(cos(2πk/256) * 32767)
    // tw_sin[k] = round(-sin(2πk/256) * 32767)   [note: negative sin for DFT]
    reg signed [15:0] tw_cos [0:127];
    reg signed [15:0] tw_sin [0:127];
    initial begin
        $readmemh(TW_FILE_COS, tw_cos);
        $readmemh(TW_FILE_SIN, tw_sin);
    end

    // ── FSM states ──
    localparam S_IDLE   = 3'd0;
    localparam S_BFLY_RD = 3'd1;  // Read butterfly operands
    localparam S_BFLY_MUL = 3'd2; // Twiddle multiply
    localparam S_BFLY_WR = 3'd3;  // Write butterfly results
    localparam S_NEXT    = 3'd4;  // Advance to next butterfly / stage
    localparam S_DONE    = 3'd5;

    reg [2:0] state;
    reg [2:0] stage;       // FFT stage (0..7)
    reg [6:0] bfly_cnt;    // Butterfly counter within stage (0..127)

    // ── Address generation ──
    // For butterfly bfly_cnt at stage s:
    //   addr_a = {bfly_cnt[6:s], 1'b0, bfly_cnt[s-1:0]}
    //   addr_b = {bfly_cnt[6:s], 1'b1, bfly_cnt[s-1:0]}
    //   tw_idx = {bfly_cnt[s-1:0], zeros(7-s)}
    reg [7:0] addr_a, addr_b;
    reg [6:0] tw_idx;

    always @(*) begin
        case (stage)
            3'd0: begin
                addr_a = {bfly_cnt, 1'b0};
                addr_b = {bfly_cnt, 1'b1};
                tw_idx = 7'd0;
            end
            3'd1: begin
                addr_a = {bfly_cnt[6:1], 1'b0, bfly_cnt[0]};
                addr_b = {bfly_cnt[6:1], 1'b1, bfly_cnt[0]};
                tw_idx = {bfly_cnt[0], 6'd0};
            end
            3'd2: begin
                addr_a = {bfly_cnt[6:2], 1'b0, bfly_cnt[1:0]};
                addr_b = {bfly_cnt[6:2], 1'b1, bfly_cnt[1:0]};
                tw_idx = {bfly_cnt[1:0], 5'd0};
            end
            3'd3: begin
                addr_a = {bfly_cnt[6:3], 1'b0, bfly_cnt[2:0]};
                addr_b = {bfly_cnt[6:3], 1'b1, bfly_cnt[2:0]};
                tw_idx = {bfly_cnt[2:0], 4'd0};
            end
            3'd4: begin
                addr_a = {bfly_cnt[6:4], 1'b0, bfly_cnt[3:0]};
                addr_b = {bfly_cnt[6:4], 1'b1, bfly_cnt[3:0]};
                tw_idx = {bfly_cnt[3:0], 3'd0};
            end
            3'd5: begin
                addr_a = {bfly_cnt[6:5], 1'b0, bfly_cnt[4:0]};
                addr_b = {bfly_cnt[6:5], 1'b1, bfly_cnt[4:0]};
                tw_idx = {bfly_cnt[4:0], 2'd0};
            end
            3'd6: begin
                addr_a = {bfly_cnt[6], 1'b0, bfly_cnt[5:0]};
                addr_b = {bfly_cnt[6], 1'b1, bfly_cnt[5:0]};
                tw_idx = {bfly_cnt[5:0], 1'd0};
            end
            3'd7: begin
                addr_a = {1'b0, bfly_cnt};
                addr_b = {1'b1, bfly_cnt};
                tw_idx = bfly_cnt;
            end
            default: begin
                addr_a = 8'd0;
                addr_b = 8'd0;
                tw_idx = 7'd0;
            end
        endcase
    end

    // ── Registered operands ──
    reg signed [DATA_W-1:0] xa_re, xa_im, xb_re, xb_im;
    reg signed [15:0] tw_c, tw_s;

    // ── Complex multiply: temp = xb * twiddle ──
    // twiddle is in Q1.15, so multiply then >>15 to get back to same scale
    wire signed [31:0] p_rr = xb_re * tw_c;
    wire signed [31:0] p_ii = xb_im * tw_s;
    wire signed [31:0] p_ri = xb_re * tw_s;
    wire signed [31:0] p_ir = xb_im * tw_c;

    wire signed [DATA_W:0] temp_re = (p_rr - p_ii + 32'sd16384) >>> 15;  // +0.5 for rounding
    wire signed [DATA_W:0] temp_im = (p_ri + p_ir + 32'sd16384) >>> 15;

    // ── Butterfly with >>1 scaling ──
    wire signed [DATA_W:0] sum_re = {xa_re[DATA_W-1], xa_re} + temp_re;
    wire signed [DATA_W:0] sum_im = {xa_im[DATA_W-1], xa_im} + temp_im;
    wire signed [DATA_W:0] dif_re = {xa_re[DATA_W-1], xa_re} - temp_re;
    wire signed [DATA_W:0] dif_im = {xa_im[DATA_W-1], xa_im} - temp_im;

    // Scale by >>1 to prevent overflow; truncate back to DATA_W bits
    wire signed [DATA_W-1:0] ya_re = sum_re >>> 1;
    wire signed [DATA_W-1:0] ya_im = sum_im >>> 1;
    wire signed [DATA_W-1:0] yb_re = dif_re >>> 1;
    wire signed [DATA_W-1:0] yb_im = dif_im >>> 1;

    // ── Output read port ──
    assign dout_re = fft_re[dout_addr];
    assign dout_im = fft_im[dout_addr];

    // ── Main FSM ──
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= S_IDLE;
            stage     <= 3'd0;
            bfly_cnt  <= 7'd0;
            busy      <= 1'b0;
            done      <= 1'b0;
            xa_re     <= 0;
            xa_im     <= 0;
            xb_re     <= 0;
            xb_im     <= 0;
            tw_c      <= 0;
            tw_s      <= 0;
        end else begin
            done <= 1'b0;

            // Input loading (bit-reversed address)
            if (din_we && state == S_IDLE) begin
                fft_re[bit_rev(din_addr)] <= din_re;
                fft_im[bit_rev(din_addr)] <= {DATA_W{1'b0}};
            end

            case (state)
                S_IDLE: begin
                    if (start) begin
                        state    <= S_BFLY_RD;
                        stage    <= 3'd0;
                        bfly_cnt <= 7'd0;
                        busy     <= 1'b1;
                    end
                end

                S_BFLY_RD: begin
                    // Read operands from BRAM (available next cycle)
                    xa_re <= fft_re[addr_a];
                    xa_im <= fft_im[addr_a];
                    xb_re <= fft_re[addr_b];
                    xb_im <= fft_im[addr_b];
                    tw_c  <= tw_cos[tw_idx];
                    tw_s  <= tw_sin[tw_idx];
                    state <= S_BFLY_MUL;
                end

                S_BFLY_MUL: begin
                    // Multiply is combinational (registered inputs from previous cycle)
                    // Results (ya/yb) are available via the combinational butterfly wires
                    state <= S_BFLY_WR;
                end

                S_BFLY_WR: begin
                    // Write butterfly results back to BRAM
                    fft_re[addr_a] <= ya_re;
                    fft_im[addr_a] <= ya_im;
                    fft_re[addr_b] <= yb_re;
                    fft_im[addr_b] <= yb_im;
                    state <= S_NEXT;
                end

                S_NEXT: begin
                    if (bfly_cnt == 7'd127) begin
                        // All butterflies in this stage done
                        bfly_cnt <= 7'd0;
                        if (stage == 3'd7) begin
                            // All stages done
                            state <= S_DONE;
                        end else begin
                            stage <= stage + 1;
                            state <= S_BFLY_RD;
                        end
                    end else begin
                        bfly_cnt <= bfly_cnt + 1;
                        state    <= S_BFLY_RD;
                    end
                end

                S_DONE: begin
                    busy <= 1'b0;
                    done <= 1'b1;
                    state <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
