// ============================================================================
// Power Spectrum + Mel Filterbank + Log2 Approximation
// ============================================================================
// After FFT completes, this module:
//   1. Iterates over frequency bins k = 0..128
//   2. Computes power: P[k] = re[k]² + im[k]²
//   3. Accumulates into 16 mel bins using triangular filter coefficients
//   4. Applies log2 approximation to each mel bin
//
// Mel filterbank coefficients stored in ROM (generated by Python).
// Each entry: {valid1, mel_idx1[3:0], coeff1[15:0], valid2, mel_idx2[3:0], coeff2[15:0]}
// (each freq bin contributes to at most 2 mel filters)
//
// Log2 uses leading-one detection + 4-bit fractional LUT.
//
// Requires: mel_coeffs.mem (129 entries, hex format)
// ============================================================================

module mel_power #(
    parameter N_FREQ  = 129,    // FFT bins 0..N/2 (256/2 + 1)
    parameter N_MELS  = 16,
    parameter MEL_FILE = "mel_coeffs.mem"
)(
    input  wire        clk,
    input  wire        rst_n,
    // Control
    input  wire        start,       // Pulse: begin processing
    output reg         busy,
    output reg         done,        // Pulse: mel values ready
    // FFT output read port
    output reg  [7:0]  fft_addr,    // Address to read from FFT
    input  wire signed [15:0] fft_re,
    input  wire signed [15:0] fft_im,
    // Mel output (read after done)
    output wire signed [15:0] mel_out,
    input  wire [3:0]  mel_addr     // 0..N_MELS-1
);

    // ── Mel filterbank coefficient ROM ──
    // Format per entry (42 bits): {v1, idx1[3:0], c1[15:0], v2, idx2[3:0], c2[15:0]}
    // Packed into 48-bit words for alignment
    reg [47:0] mel_rom [0:N_FREQ-1];
    initial $readmemh(MEL_FILE, mel_rom);

    // ── Mel accumulators (one per mel bin) ──
    reg [47:0] mel_acc [0:N_MELS-1];

    // ── Log-mel results ──
    reg signed [15:0] mel_log [0:N_MELS-1];
    assign mel_out = mel_log[mel_addr];

    // ── FSM ──
    localparam S_IDLE    = 3'd0;
    localparam S_READ    = 3'd1;  // Set FFT address
    localparam S_WAIT    = 3'd2;  // Wait for BRAM read latency
    localparam S_COMPUTE = 3'd3;  // Compute power + accumulate
    localparam S_LOG_RD  = 3'd4;  // Register mel accumulator for log2
    localparam S_LOG_WR  = 3'd5;  // Write log2 result
    localparam S_DONE    = 3'd6;

    reg [2:0]  state;
    reg [7:0]  freq_idx;       // 0..128
    reg [3:0]  log_idx;        // 0..15

    // Registered FFT data
    reg signed [15:0] re_reg, im_reg;

    // Power computation
    wire signed [31:0] re_sq = re_reg * re_reg;
    wire signed [31:0] im_sq = im_reg * im_reg;
    wire        [31:0] power = re_sq[31:0] + im_sq[31:0]; // Always positive

    // Mel coefficient decode
    wire [47:0] mel_entry = mel_rom[freq_idx];
    // Bit layout matches export_coefficients.py:
    // v1(1) | idx1(4) | c1(16) | v2(1) | idx2(4) | c2(16) | pad(6)
    wire        v1    = mel_entry[47];
    wire [3:0]  idx1  = mel_entry[46:43];
    wire [15:0] c1    = mel_entry[42:27];
    wire        v2    = mel_entry[26];
    wire [3:0]  idx2  = mel_entry[25:22];
    wire [15:0] c2    = mel_entry[21:6];

    // Power × coefficient (32 × 16 = 48 bit product, take upper 32 bits)
    wire [47:0] prod1 = power * c1;
    wire [47:0] prod2 = power * c2;

    // ── Log2 approximation ──
    // log2(x) ≈ MSB_position + fractional_LUT[next_4_bits]
    // Output in Q8.8 fixed-point (8 integer bits, 8 fractional bits)
    reg [47:0] log_input;
    reg [5:0]  msb_pos;
    reg [3:0]  frac_bits;

    // Log2 fractional LUT (16 entries, 8-bit fractional values)
    // LUT[i] = round(log2(1 + i/16) * 256)
    wire [7:0] log_frac_lut [0:15];
    assign log_frac_lut[0]  = 8'd0;
    assign log_frac_lut[1]  = 8'd11;
    assign log_frac_lut[2]  = 8'd22;
    assign log_frac_lut[3]  = 8'd33;
    assign log_frac_lut[4]  = 8'd43;
    assign log_frac_lut[5]  = 8'd53;
    assign log_frac_lut[6]  = 8'd63;
    assign log_frac_lut[7]  = 8'd73;
    assign log_frac_lut[8]  = 8'd82;
    assign log_frac_lut[9]  = 8'd91;
    assign log_frac_lut[10] = 8'd100;
    assign log_frac_lut[11] = 8'd109;
    assign log_frac_lut[12] = 8'd117;
    assign log_frac_lut[13] = 8'd125;
    assign log_frac_lut[14] = 8'd134;
    assign log_frac_lut[15] = 8'd141;

    // Find MSB position (priority encoder)
    integer b;
    always @(*) begin
        msb_pos   = 6'd0;
        frac_bits = 4'd0;
        for (b = 47; b >= 0; b = b - 1) begin
            if (log_input[b] && msb_pos == 0 && b > 0) begin
                msb_pos = b[5:0];
            end
        end
        // Extract 4 bits below MSB for fractional lookup
        if (msb_pos >= 4)
            frac_bits = log_input[msb_pos-1 -: 4];
        else
            frac_bits = log_input[3:0];
    end

    wire signed [15:0] log2_result = (log_input == 0) ? -16'sd8192 :
                                     {2'b0, msb_pos, log_frac_lut[frac_bits]};

    integer j;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= S_IDLE;
            freq_idx <= 0;
            log_idx  <= 0;
            busy     <= 1'b0;
            done     <= 1'b0;
            fft_addr <= 0;
            re_reg   <= 0;
            im_reg   <= 0;
            for (j = 0; j < N_MELS; j = j + 1) begin
                mel_acc[j] <= 0;
                mel_log[j] <= 0;
            end
        end else begin
            done <= 1'b0;

            case (state)
                S_IDLE: begin
                    if (start) begin
                        state    <= S_READ;
                        freq_idx <= 0;
                        busy     <= 1'b1;
                        for (j = 0; j < N_MELS; j = j + 1)
                            mel_acc[j] <= 0;
                    end
                end

                S_READ: begin
                    // Request FFT data for current frequency bin
                    fft_addr <= freq_idx;
                    state    <= S_WAIT;
                end

                S_WAIT: begin
                    // Register FFT data (1-cycle BRAM latency)
                    re_reg <= fft_re;
                    im_reg <= fft_im;
                    state  <= S_COMPUTE;
                end

                S_COMPUTE: begin
                    // Accumulate power × coefficient into mel bins
                    if (v1) mel_acc[idx1] <= mel_acc[idx1] + prod1;
                    if (v2) mel_acc[idx2] <= mel_acc[idx2] + prod2;

                    if (freq_idx == N_FREQ - 1) begin
                        // All frequency bins processed → compute log
                        state   <= S_LOG_RD;
                        log_idx <= 0;
                    end else begin
                        freq_idx <= freq_idx + 1;
                        state    <= S_READ;
                    end
                end

                S_LOG_RD: begin
                    // Register mel accumulator value (available next cycle)
                    log_input <= mel_acc[log_idx];
                    state     <= S_LOG_WR;
                end

                S_LOG_WR: begin
                    // log2_result is now valid (depends on registered log_input)
                    mel_log[log_idx] <= log2_result;

                    if (log_idx == N_MELS - 1) begin
                        state <= S_DONE;
                    end else begin
                        log_idx <= log_idx + 1;
                        state   <= S_LOG_RD;
                    end
                end

                S_DONE: begin
                    busy <= 1'b0;
                    done <= 1'b1;
                    state <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
